<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<IEnumerable<EasyUI.Web.Mvc.JavaScriptTests.Customer>>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <%= Html.EasyUI().Grid(Model).Name("AutoGeneratedColumns")
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("AutoGeneratedColumnsWithScrolling")
            .Scrollable()
            .Pageable()%>
    
    <%= Html.EasyUI().Grid(Model).Name("ManyColumns")
            .Columns(columns => {
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Name);                
            })
            .Scrollable()
            .Pageable()%>
    
    <%= Html.EasyUI().Grid(Model).Name("Grouping")
            .Groupable(g => g.Groups(c => c.Add(x => x.Name)))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Grid"))
            .Pageable() %>
    
    
    <%= Html.EasyUI().Grid(Model).Name("Grouping_active")
            .Groupable(g => g.Groups(c => c.Add(x => x.Name)))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Grid"))
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("GroupingWithScrolling")
            .Groupable(g => g.Groups(c => c.Add(x => x.Name)))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Grid"))
            .Scrollable()
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("GroupingWithScrolling_active")
            .Groupable(g => g.Groups(c => c.Add(x => x.Name)))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Grid"))
            .Scrollable()
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("Editing")
            .DataKeys(conf => conf.Add(x => x.Name))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Dummy").Insert("Insert", "Dummy").Delete("Delete", "Dummy").Update("Update", "Dummy"))
            .Columns(columns =>
            {
                columns.Bound(c => c.Name);
                columns.Bound(c => c.BirthDate);
                columns.Bound(c => c.Active);
                columns.Command(conf =>
                {
                    conf.Edit();
                    conf.Delete();
                });
            })
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("Editing_active")
            .DataKeys(conf => conf.Add(x => x.Name))
            .DataBinding(binding => binding.Ajax().Select("Select", "Dummy").Insert("Insert", "Dummy").Delete("Delete", "Dummy").Update("Update", "Dummy"))
            .Columns(columns =>
            {
                columns.Bound(c => c.Name);
                columns.Bound(c => c.BirthDate);
                columns.Bound(c => c.Active);
                columns.Command(conf =>
                {
                    conf.Edit();
                    conf.Delete();
                });
            })
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("EditingWithScrolling")
            .DataKeys(conf => conf.Add(x => x.Name))
            .DataBinding(binding => binding.Ajax().Select("Select", "Dummy").Insert("Insert", "Dummy").Delete("Delete", "Dummy").Update("Update", "Dummy"))
            .Columns(columns =>
            {
                columns.Bound(c => c.Name);
                columns.Bound(c => c.BirthDate);
                columns.Bound(c => c.Active);
                columns.Command(conf => {
                    conf.Edit();
                    conf.Delete();
                });
            })
            .Scrollable()
            .Pageable() %>
    
    <%= Html.EasyUI().Grid(Model).Name("GroupingWithEditingAndScrolling")
            .Groupable(g => g.Groups(c => c.Add(x => x.Name)))
            .DataKeys(conf => conf.Add(x => x.Name))
            .DataBinding(binding => binding.Ajax().Select("GroupingAjax", "Grid").Insert("Insert", "Dummy").Delete("Delete", "Dummy").Update("Update", "Dummy"))
            .Columns(columns =>
            {
                columns.Bound(c => c.Name);
                columns.Bound(c => c.BirthDate);
                columns.Bound(c => c.Active);
                columns.Command(conf => {
                    conf.Edit();
                    conf.Delete();
                });
            })
            .Scrollable()
            .Pageable() %>

</asp:Content>


<asp:Content ContentPlaceHolderID="TestContent" runat="server">

<script type="text/javascript">

        function getGrid(selector) {
            return $(selector).data("tGrid");
        }
        
        function isSyncedLayout(selector) {
            var $grid = $(selector);
            
            var headerCells = $grid.find('.t-header');
            var firstRowCells = $grid.find('.t-grid-content tbody tr:not(.t-grouping-row)').eq(0).find('td');
            
            if (firstRowCells.length == 0)
                firstRowCells = $grid.find('tbody tr:not(.t-grouping-row)').eq(0).find('td');
            
            if (firstRowCells.hasClass('t-edit-container'))
                firstRowCells = firstRowCells.find('td');
            
            return headerCells
                .filter(function(index) {
                   return this.offsetWidth == firstRowCells[index].offsetWidth;
                }).length == headerCells.length;
        }

        test('AutoGeneratedColumns initial layout is synced', function() {
            ok(isSyncedLayout('#AutoGeneratedColumns'));
        });

        test('AutoGeneratedColumnsWithScrolling initial layout is synced', function() {
            ok(isSyncedLayout('#AutoGeneratedColumnsWithScrolling'));
        });

        test('Grouping initial layout is synced', function() {
            ok(isSyncedLayout('#Grouping'));
        });

        test('GroupingWithScrolling initial layout is synced', function() {
            ok(isSyncedLayout('#GroupingWithScrolling'));
        });

        test('Editing initial layout is synced', function() {
            ok(isSyncedLayout('#Editing'));
        });
        
        test('Grouping layout after ungroup is synced', function() {
            var grid = getGrid('#Grouping_active');            
            grid.unGroup('Name');
            grid.normalizeColumns();
            
            ok(isSyncedLayout('#Grouping_active'));
        });

</script>

</asp:Content>