//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUI.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridLocalization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyUI.Web.Mvc.Resources.GridLocalization", typeof(GridLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加记录 的本地化字符串。
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消更改 的本地化字符串。
        /// </summary>
        internal static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定删除该条记录吗? 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示项 {0} - {1} 当前{2} 的本地化字符串。
        /// </summary>
        internal static string DisplayingItems {
            get {
                return ResourceManager.GetString("DisplayingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两者 的本地化字符串。
        /// </summary>
        internal static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string FilterBoolIsFalse {
            get {
                return ResourceManager.GetString("FilterBoolIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string FilterBoolIsTrue {
            get {
                return ResourceManager.GetString("FilterBoolIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除筛选 的本地化字符串。
        /// </summary>
        internal static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        internal static string FilterDateEq {
            get {
                return ResourceManager.GetString("FilterDateEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        internal static string FilterDateGe {
            get {
                return ResourceManager.GetString("FilterDateGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        internal static string FilterDateGt {
            get {
                return ResourceManager.GetString("FilterDateGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        internal static string FilterDateLe {
            get {
                return ResourceManager.GetString("FilterDateLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        internal static string FilterDateLt {
            get {
                return ResourceManager.GetString("FilterDateLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        internal static string FilterDateNe {
            get {
                return ResourceManager.GetString("FilterDateNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        internal static string FilterEnumEq {
            get {
                return ResourceManager.GetString("FilterEnumEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        internal static string FilterEnumNe {
            get {
                return ResourceManager.GetString("FilterEnumNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        internal static string FilterNumberEq {
            get {
                return ResourceManager.GetString("FilterNumberEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于或 的本地化字符串。
        /// </summary>
        internal static string FilterNumberGe {
            get {
                return ResourceManager.GetString("FilterNumberGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        internal static string FilterNumberGt {
            get {
                return ResourceManager.GetString("FilterNumberGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于或等于 的本地化字符串。
        /// </summary>
        internal static string FilterNumberLe {
            get {
                return ResourceManager.GetString("FilterNumberLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于或 的本地化字符串。
        /// </summary>
        internal static string FilterNumberLt {
            get {
                return ResourceManager.GetString("FilterNumberLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        internal static string FilterNumberNe {
            get {
                return ResourceManager.GetString("FilterNumberNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -选择值- 的本地化字符串。
        /// </summary>
        internal static string FilterSelectValue {
            get {
                return ResourceManager.GetString("FilterSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示行 的本地化字符串。
        /// </summary>
        internal static string FilterShowRows {
            get {
                return ResourceManager.GetString("FilterShowRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾 的本地化字符串。
        /// </summary>
        internal static string FilterStringEndsWith {
            get {
                return ResourceManager.GetString("FilterStringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        internal static string FilterStringEq {
            get {
                return ResourceManager.GetString("FilterStringEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        internal static string FilterStringNe {
            get {
                return ResourceManager.GetString("FilterStringNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头 的本地化字符串。
        /// </summary>
        internal static string FilterStringStartsWith {
            get {
                return ResourceManager.GetString("FilterStringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包涵 的本地化字符串。
        /// </summary>
        internal static string FilterStringSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖动列头分组排布 的本地化字符串。
        /// </summary>
        internal static string GroupHint {
            get {
                return ResourceManager.GetString("GroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无记录显示. 的本地化字符串。
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 {0} 的本地化字符串。
        /// </summary>
        internal static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改 的本地化字符串。
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正序排列 的本地化字符串。
        /// </summary>
        internal static string SortedAsc {
            get {
                return ResourceManager.GetString("SortedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒序排列 的本地化字符串。
        /// </summary>
        internal static string SortedDesc {
            get {
                return ResourceManager.GetString("SortedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不分组 的本地化字符串。
        /// </summary>
        internal static string UnGroup {
            get {
                return ResourceManager.GetString("UnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
