//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUI.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyUI.Web.Mvc.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; array cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string ArrayCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArrayCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must use InCell edit mode for batch updates. 的本地化字符串。
        /// </summary>
        internal static string BatchUpdatesRequireInCellMode {
            get {
                return ResourceManager.GetString("BatchUpdatesRequireInCellMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Update data binding setting is required for batch updates. Please specify the Update action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string BatchUpdatesRequireUpdate {
            get {
                return ResourceManager.GetString("BatchUpdatesRequireUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNegative {
            get {
                return ResourceManager.GetString("CannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be negative or zero. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("CannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be null. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find a public property of primitive type to sort by. 的本地化字符串。
        /// </summary>
        internal static string CannotFindPropertyToSortBy {
            get {
                return ResourceManager.GetString("CannotFindPropertyToSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot have more one column in order when sort mode is set to single column. 的本地化字符串。
        /// </summary>
        internal static string CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn {
            get {
                return ResourceManager.GetString("CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot route to class named &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotRouteToClassNamedController {
            get {
                return ResourceManager.GetString("CannotRouteToClassNamedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use Ajax and WebService binding at the same time. 的本地化字符串。
        /// </summary>
        internal static string CannotUseAjaxAndWebServiceAtTheSameTime {
            get {
                return ResourceManager.GetString("CannotUseAjaxAndWebServiceAtTheSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use PageOnScroll with Server binding. 的本地化字符串。
        /// </summary>
        internal static string CannotUsePageOnScrollWithServerBinding {
            get {
                return ResourceManager.GetString("CannotUsePageOnScrollWithServerBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use only server templates in Ajax or WebService binding mode. Please specify a client template as well. 的本地化字符串。
        /// </summary>
        internal static string CannotUseTemplatesInAjaxOrWebService {
            get {
                return ResourceManager.GetString("CannotUseTemplatesInAjaxOrWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; collection cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{1} 的本地化字符串。
        /// </summary>
        internal static string ControllerNameAmbiguousWithoutRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{2} 的本地化字符串。
        /// </summary>
        internal static string ControllerNameAmbiguousWithRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller name must end with &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string ControllerNameMustEndWithController {
            get {
                return ResourceManager.GetString("ControllerNameMustEndWithController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DataKeys collection is empty. Please specify a data key. 的本地化字符串。
        /// </summary>
        internal static string DataKeysEmpty {
            get {
                return ResourceManager.GetString("DataKeysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTable InLine editing and custom EditorTemplate per column is not supported 的本地化字符串。
        /// </summary>
        internal static string DataTableInLineEditingWithCustomEditorTemplates {
            get {
                return ResourceManager.GetString("DataTableInLineEditingWithCustomEditorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Delete data binding setting is required by the delete command. Please specify the Delete action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string DeleteCommandRequiresDelete {
            get {
                return ResourceManager.GetString("DeleteCommandRequiresDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Update data binding setting is required by the edit command. Please specify the Update action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string EditCommandRequiresUpdate {
            get {
                return ResourceManager.GetString("EditCommandRequiresUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be bigger then {1}. 的本地化字符串。
        /// </summary>
        internal static string FirstPropertyShouldNotBeBiggerThenSecondProperty {
            get {
                return ResourceManager.GetString("FirstPropertyShouldNotBeBiggerThenSecondProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group with specified name already exists. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group with specified name &quot;{0}&quot; already exists. Please specify a different name. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group with &quot;{0}&quot; does not exist in {1} SharedWebAssets. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group with specified name &quot;{0}&quot; does not exist. Please make sure you have specified a correct name. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InCell editing mode is not supported in server binding mode 的本地化字符串。
        /// </summary>
        internal static string InCellModeNotSupportedInServerBinding {
            get {
                return ResourceManager.GetString("InCellModeNotSupportedInServerBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InCell editing mode is not supported when ClientRowTemplate is used 的本地化字符串。
        /// </summary>
        internal static string InCellModeNotSupportedWithRowTemplate {
            get {
                return ResourceManager.GetString("InCellModeNotSupportedWithRowTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provided index is out of range. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Insert data binding setting is required by the insert command. Please specify the Insert action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string InsertCommandRequiresInsert {
            get {
                return ResourceManager.GetString("InsertCommandRequiresInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item with specified source already exists. 的本地化字符串。
        /// </summary>
        internal static string ItemWithSpecifiedSourceAlreadyExists {
            get {
                return ResourceManager.GetString("ItemWithSpecifiedSourceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local group with name &quot;{0}&quot; already exists. 的本地化字符串。
        /// </summary>
        internal static string LocalGroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("LocalGroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key with the following name &quot;{0}&quot; was not found. Please update all localization files. 的本地化字符串。
        /// </summary>
        internal static string LocalizationKeyNotFound {
            get {
                return ResourceManager.GetString("LocalizationKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bound columns require a field or property access expression. 的本地化字符串。
        /// </summary>
        internal static string MemberExpressionRequired {
            get {
                return ResourceManager.GetString("MemberExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be less than {1}. 的本地化字符串。
        /// </summary>
        internal static string MinPropertyMustBeLessThenMaxProperty {
            get {
                return ResourceManager.GetString("MinPropertyMustBeLessThenMaxProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot be blank. 的本地化字符串。
        /// </summary>
        internal static string NameCannotBeBlank {
            get {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot contain spaces. 的本地化字符串。
        /// </summary>
        internal static string NameCannotContainSpaces {
            get {
                return ResourceManager.GetString("NameCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;None&quot; is only used for internal purpose. 的本地化字符串。
        /// </summary>
        internal static string NoneIsOnlyUsedForInternalPurpose {
            get {
                return ResourceManager.GetString("NoneIsOnlyUsedForInternalPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one ScriptRegistrar is allowed in a single request. 的本地化字符串。
        /// </summary>
        internal static string OnlyOneScriptRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneScriptRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one StyleSheetRegistrar is allowed in a single request. 的本地化字符串。
        /// </summary>
        internal static string OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only property and field expressions are supported 的本地化字符串。
        /// </summary>
        internal static string OnlyPropertyAndFieldExpressionsAreSupported {
            get {
                return ResourceManager.GetString("OnlyPropertyAndFieldExpressionsAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paging must be enabled to use PageOnScroll. 的本地化字符串。
        /// </summary>
        internal static string PagingMustBeEnabledToUsePageOnScroll {
            get {
                return ResourceManager.GetString("PagingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} must be begger then 0. 的本地化字符串。
        /// </summary>
        internal static string PropertyMustBeBiggerThenZero {
            get {
                return ResourceManager.GetString("PropertyMustBeBiggerThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be positive number. 的本地化字符串。
        /// </summary>
        internal static string PropertyMustBePositiveNumber {
            get {
                return ResourceManager.GetString("PropertyMustBePositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be bigger than {1} and less then {2} 的本地化字符串。
        /// </summary>
        internal static string PropertyShouldBeInRange {
            get {
                return ResourceManager.GetString("PropertyShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &quot;{0}&quot; class is no longer supported. To enable RTL support you must include EasyUI.rtl.css and apply the &quot;t-rtl&quot; class to a parent HTML element or the &lt;body&gt;. 的本地化字符串。
        /// </summary>
        internal static string Rtl {
            get {
                return ResourceManager.GetString("Rtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrolling must be enabled to use PageOnScroll. 的本地化字符串。
        /// </summary>
        internal static string ScrollingMustBeEnabledToUsePageOnScroll {
            get {
                return ResourceManager.GetString("ScrollingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must have SiteMap defined with key &quot;{0}&quot; in ViewData dictionary. 的本地化字符串。
        /// </summary>
        internal static string SiteMapShouldBeDefinedInViewData {
            get {
                return ResourceManager.GetString("SiteMapShouldBeDefinedInViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source must be a virtual path which should starts with &quot;~/&quot; 的本地化字符串。
        /// </summary>
        internal static string SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash {
            get {
                return ResourceManager.GetString("SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified file does not exist: &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string SpecifiedFileDoesNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed string cannot be parsed to DateTime object. 的本地化字符串。
        /// </summary>
        internal static string StringNotCorrectDate {
            get {
                return ResourceManager.GetString("StringNotCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed string cannot be parsed to TimeSpan object. 的本地化字符串。
        /// </summary>
        internal static string StringNotCorrectTimeSpan {
            get {
                return ResourceManager.GetString("StringNotCorrectTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified method is not an action method. 的本地化字符串。
        /// </summary>
        internal static string TheSpecifiedMethodIsNotAnActionMethod {
            get {
                return ResourceManager.GetString("TheSpecifiedMethodIsNotAnActionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time should be bigger than MinTime and less than MaxTime. 的本地化字符串。
        /// </summary>
        internal static string TimeOutOfRange {
            get {
                return ResourceManager.GetString("TimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot set Url and ContentUrl at the same time. 的本地化字符串。
        /// </summary>
        internal static string UrlAndContentUrlCannotBeSet {
            get {
                return ResourceManager.GetString("UrlAndContentUrlCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Url of the WebService must be set 的本地化字符串。
        /// </summary>
        internal static string WebServiceUrlRequired {
            get {
                return ResourceManager.GetString("WebServiceUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot add more than once column when sort mode is set to single column. 的本地化字符串。
        /// </summary>
        internal static string YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle {
            get {
                return ResourceManager.GetString("YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use non generic BindTo overload without EnableCustomBinding set to true 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallBindToWithoutCustomBinding {
            get {
                return ResourceManager.GetString("YouCannotCallBindToWithoutCustomBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot call render more than once. 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallRenderMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallRenderMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot call Start more than once. 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallStartMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallStartMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot configure a shared web asset group. 的本地化字符串。
        /// </summary>
        internal static string YouCannotConfigureASharedWebAssetGroup {
            get {
                return ResourceManager.GetString("YouCannotConfigureASharedWebAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must have to call Start prior calling this method. 的本地化字符串。
        /// </summary>
        internal static string YouMustHaveToCallStartPriorCallingThisMethod {
            get {
                return ResourceManager.GetString("YouMustHaveToCallStartPriorCallingThisMethod", resourceCulture);
            }
        }
    }
}
